### ISSUE TITLE
Mood=Ind and others appear to require documentation

### ISSUE THREAD

**Issue by Traubert** [UniversalDependencies/docs-automation#1]
Many universal values of features, such as Mood=Ind, are causing errors to appear in eg. the Akkadian RIAO corpus (see http://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/validation-report.pl?UD_Akkadian-RIAO). Do I understand correctly that they are not supposed to require documentation and this is a bug?

**Comment by dan-zeman** [comment]
This is not a bug. Documentation for the `Mood` feature is not required as long as only the universally defined values are used.

If language-specific documentation of a feature exists, it replaces any globally available documentation of that feature. In such cases, the universal values that are relevant for the language must be also listed in the language-specific documentation. This is currently the case of Akkadian: [Mood is described here](https://universaldependencies.org/akk/feat/Mood.html), so the universal documentation is no longer relevant and `Mood=Ind` is not allowed because the Akkadian specific page does not list it. (Of course, if the local documentation lists it, it should be compatible with the universal definition, but that is something that the script cannot verify.)

BTW, I would advise against feature values longer than about 5 characters; specifically, the values in UD features don't include the _-ative_ / _-itive_ suffix from the actual linguistic term. And if the language-specific value ever makes it to the universal guidelines, it will certainly not use a string like `Precative` or `Prohibitive`; I suppose that `Prec` and `Proh` are more likely. In fact, these seem to be already used in Erzya and Moksha but unfortunately they are not yet documented. Once they are documented and it turns out they indeed mean precative and prohibitive, respectively, the documentation checker will probably prohibit the longer versions in the interest of labeling the same phenomenon using the same string.
